openapi: 3.0.0
info:
  version: 1.0.0
  title: レシピ管理アプリケーションのバックエンドAPI

tags:
  - name: Recipes
    description: レシピ関連のエンドポイント

paths:
  '/api/recipes/{id}':
    get:
      tags:
        - Recipes
      summary: "レシピ情報API"
      description: 特定のレシピの詳細情報を取得する。
      parameters:
        - name: id
          in: path
          description: 取得するレシピのID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: レシピのID
                    example: 1
                  title:
                    type: string
                    description: レシピ名
                    example: "簡単！おいしいカレーライス"
                  servings:
                    type: integer
                    description: このレシピが何人分の料理かを示します。例えば、2と記載されている場合は、2人分の分量を表します。
                    example: 3
                  ingredients:
                    type: array
                    items:
                      $ref: '#/components/schemas/Ingredients'
                  videoUrl:
                    type: string
                    description: レシピ動画のURL
                    example: "https://www.youtube.com/watch?v=XXXXXXXXXX"
                  steps:
                    type: array
                    items:
                      $ref: '#/components/schemas/Steps'
                  point:
                    type: string
                    description: レシピのポイントやコツを示します。調理の際に役立つ具体的なアドバイスや工夫を記載できます。
                    example: "お肉を焼く前に常温に戻すと、よりジューシーになります！"

components:
  schemas:
    Ingredients:
      type: object
      properties:
        id:
          type: integer
          description: 材料のID
          example: 1
        name:
          type: string
          description: 材料名
          example: "玉ねぎ"
        amount:
          type: string
          description: 材料の量
          example: "2個"
    Steps:
      type: object
      properties:
        id:
          type: integer
          description: 各工程のID
          example: 1
        stepNumber:
          type: integer
          description: 工程の順番（数値）
          example: 1
        description:
          type: string
          description: 具体的な作業内容や手順の説明
          example: "玉ねぎをみじん切りにします。"