swagger: '2.0'
info:
  version: 1.0.0
  title: タイトル
paths:
  '/api/recipes/{id}':
    get:
      description: 特定のレシピの詳細情報を取得する。
      parameters:
        - name: id
          in: path
          description: 取得するレシピのID
          required: true
          type: number
      responses:
        '200':
          description: 成功
          schema:
            type: object
            properties:
              id:
                type: integer
              title:
                type: string
              servings:
                type: integer