openapi: 3.0.0
info:
  version: 1.0.0
  title: レシピ管理アプリケーションのバックエンドAPI

tags:
  - name: Recipes
    description: レシピ関連のエンドポイント

paths:
  '/api/recipes/{id}':
    get:
      tags:
        - Recipes
      summary: "レシピ情報API"
      description: 特定のレシピの詳細情報を取得する。
      parameters:
        - name: id
          in: path
          description: 取得するレシピのID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: レシピのID
                  title:
                    type: string
                    description: レシピ名
                  servings:
                    type: string
                    description: このレシピが何人分の料理かを示します。例えば、2と記載されている場合は、2人分の分量を表します。
                  ingredients:
                    type: array
                    items:
                      $ref: '#/components/schemas/Ingredients'

components:
  schemas:
    Ingredients:
      type: object
      properties:
        id:
          type: integer
          description: 材料のID
        name:
          type: string
          description: 材料名
        amount:
          type: string
          description: 材料の量